<?xml version="1.0"?>
<robot name="valve_description" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="side" value="0.22" />
  <xacro:property name="z_offset_box" value="${0.0615}" />
  <xacro:property name="spacer_radius" value="0.011" />
  <xacro:property name="spacer_height" value="0.072" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="0.02" length="0.05"/>
      </geometry>
      <origin xyz="0 ${side/2} ${z_offset_box + side/2}" rpy="${pi/2} 0 0" />
    </visual>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
  </link>

  <link name="box">
    <visual>
      <geometry>
        <box size="${side} ${side} ${side}"/>
      </geometry>
      <inertial>
        <mass value="10"/>
        <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
      </inertial>
      <material name="white"/>
    </visual>
  </link>

  <joint name="box_incline" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
    <parent link="base_link"/>
    <child link="box"/>
    <origin xyz="0 0 ${z_offset_box + side/2}" rpy="0 0 0" />
  </joint>

  <link name="spacer">
    <visual>
      <geometry>
        <cylinder radius="${spacer_radius}" length="${spacer_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${spacer_radius}" length="${spacer_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <joint name="spacerbox" type="fixed">
    <parent link="box"/>
    <child link="spacer"/>
    <origin xyz="0 0 ${side/2 + spacer_height/2}"/>
  </joint>

  <link name="handwheel">
    <visual>
      <geometry>
        <mesh filename="package://valve_description/mesh/handwheel_245900116_stl.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://valve_description/mesh/handwheel_245900116_stl.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
      <inertial>
      <mass value="10"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <joint name="wheel_rotation" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi}" velocity="0.5"/>
    <parent link="spacer"/>
    <child link="handwheel"/>
    <origin xyz="0 0 ${spacer_height/2}"/>
  </joint>

</robot>
